// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMrBL9WM8k7rwUCgdqFZqlQL1NKK9IWM4',
    appId: '1:92600497462:web:a56dd7ead2dd4f4bd6ef97',
    messagingSenderId: '92600497462',
    projectId: 'flutter-firebase-22e58',
    authDomain: 'flutter-firebase-22e58.firebaseapp.com',
    storageBucket: 'flutter-firebase-22e58.appspot.com',
    measurementId: 'G-EQ8HKCJ7FM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsl9SMLD0YAUiLUXvPh4nx7eXQ_ec8RwE',
    appId: '1:92600497462:android:b30876b4f17abdadd6ef97',
    messagingSenderId: '92600497462',
    projectId: 'flutter-firebase-22e58',
    storageBucket: 'flutter-firebase-22e58.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCE-5b4a8ake71Ch6heSPYmYtjvLA74j20',
    appId: '1:92600497462:ios:91250e451562f67dd6ef97',
    messagingSenderId: '92600497462',
    projectId: 'flutter-firebase-22e58',
    storageBucket: 'flutter-firebase-22e58.appspot.com',
    androidClientId: '92600497462-9um6jqakih7a0fd4m4jtv9kk2a3a6rrs.apps.googleusercontent.com',
    iosClientId: '92600497462-e2qcbdov6ijfiacifitqopfhj3ihogp5.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCE-5b4a8ake71Ch6heSPYmYtjvLA74j20',
    appId: '1:92600497462:ios:e100cf3bebc213d0d6ef97',
    messagingSenderId: '92600497462',
    projectId: 'flutter-firebase-22e58',
    storageBucket: 'flutter-firebase-22e58.appspot.com',
    androidClientId: '92600497462-9um6jqakih7a0fd4m4jtv9kk2a3a6rrs.apps.googleusercontent.com',
    iosClientId: '92600497462-aeo2tc61gp37brir4ravr378a5j0ugn7.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebase.RunnerTests',
  );
}
